// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe_8LhlWmuNtTddJ9sSOb14tUzqtlXVvI',
    appId: '1:483742683267:web:f5a781e1db3494de610bb6',
    messagingSenderId: '483742683267',
    projectId: 'fddn11',
    authDomain: 'fddn11.firebaseapp.com',
    storageBucket: 'fddn11.firebasestorage.app',
    measurementId: 'G-S079D7PH9W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA479PCqPEjsnmTpMXTIZmsY8O4RFvbv_M',
    appId: '1:483742683267:android:1343bd59bef20dbd610bb6',
    messagingSenderId: '483742683267',
    projectId: 'fddn11',
    storageBucket: 'fddn11.firebasestorage.app',
  );
}
